name: "Push notification from Github on Whatsapp"
description: "Sends a Whatsapp message when a push event occurs"
author: "TSC"
branding:
  icon: message-square
  color: green

runs:
  using: "docker"
  image: "Dockerfile"
  

